### PR TITLE
Laddermen arrow damage mitigation

### PR DESCRIPTION
**Pull request by LordHansCapon**
Increases laddermen arrow damage resistance while they are using their ladder on a wall.

**Melee, fire and stone damage does not change!**

Laddermen take 1000 damage from one arrow. While holding the ladder against a wall, they take 250.
This change reduces it to 125.

#226 

**Test build:**
https://we.tl/t-tgZ3iQtZll

### CODE REVIEW

**Comment by ByBurton** [comment]
By how much does the resistance change?

**Comment by LordHansCapon** [comment]
> By how much does the resistance change?

Ah yes, sorry, so the damage was divided by 4 by default, now it is divided by 8. So effectively doubled their resistance.

Laddermen take 1000 damage from arrow, while holding the ladder, they take 250. This change reduces it to 125.

**Comment by GRhin** [comment]
Just a dummy check cos I cant understand the code, other times I see divided by 4 in the code it was divided by 2 twice, are you certain that you divided this by 2 only once more to get 8, or did you divide by 2 twice more, which would be dividing by 16.
Again, just a dummy check, it's an easy mistake to make if your not paying attention.

**Comment by LordHansCapon** [comment]
> Just a dummy check cos I cant understand the code, other times I see divided by 4 in the code it was divided by 2 twice, are you certain that you divided this by 2 only once more to get 8, or did you divide by 2 twice more, which would be dividing by 16.
> Again, just a dummy check, it's an easy mistake to make if your not paying attention.

I have increased the Arithmetic Right Bit Shift from 2 to 3. Using a calculator, right shifting decimal 1000 results in 125.
image

So that is correct. I have also checked it in-game. However, this value can be skewed by the **Increased armor  of laddermen against ranged units** which reduces damage regardless of the ladderman's current state.

**Comment by Krarilotus** [comment]
did this get an update in description and ordering in the bugfix list, to be next to the other one? (as requested in discord...) 
Otherwise this works fine, and we can probably merge. Would just like to test one more time :D

**Comment by LordHansCapon** [comment]
@Krarilotus It haven't, will do tonight! :)

**Comment by patel-nikhil** [comment]
> However, this value can be skewed by the Increased armor of laddermen against ranged units which reduces damage regardless of the ladderman's current state.

I am thinking that it would be better to have a single option 'Increase laddermen armor' and then suboptions such as:
 - Against only arrows when against wall
 - Against all ranged attacks

**Comment by GRhin** [comment]
Problem is the rate of increase is different for each situation, I think it will cause less confusion if they are kept separate.

**Comment by Krarilotus** [comment]
Doesn't work with Crossbowbolts either. Is that intended? OTherwise works vs archers as intended!

**Comment by LordHansCapon** [comment]
@Krarilotus Thats unintended, might look into it.

**Comment by Krarilotus** [comment]
this will be revisited once we have the balance module in the new patcher. Sorry but y, there hasn't been much correspondence about stuff here lately, so ill close it. You can ofc redo a new pull request once its updated :)

**Pull request closed without merging**
