### PR TITLE
Added Restore AI Siege messages

### PR DESCRIPTION
**Pull request by LordHansCapon**
AIs have recorded Siege messages which they send to their allies when they are about to attack an enemy. This feature was cut from the game, but the assets remained.

This option restores this feature.

image

grafik

#122 

**Test build:**
https://we.tl/t-NHQSEIVTPa

### CODE REVIEW

**Comment by Monsterfisch** [comment]
tested on SHC extreme and works as intended.

I do understand why it was scrapped, however .. so i suggest maybe adding a condition to the triggering of the message otherwise you will hear it ...aloot
one idea would be to start sending these messages after a certain amount of attacks so the army sizes have grown are big enough that the attacks don't happen every half a minute. 
Another way would be to limit it to every other attack or make it depend on a difference between attacking army and defender so if the enemy on paper has fewer troops available than the attacker (making the attacker confident) he messages the player/his allies to join in on the siege.

**Comment by LordHansCapon** [comment]
> tested on SHC extreme and works as intended.
> 
> I do understand why it was scrapped, however .. so i suggest maybe adding a condition to the triggering of the message otherwise you will hear it ...aloot
> one idea would be to start sending these messages after a certain amount of attacks so the army sizes have grown are big enough that the attacks don't happen every half a minute.
> Another way would be to limit it to every other attack or make it depend on a difference between attacking army and defender so if the enemy on paper has fewer troops available than the attacker (making the attacker confident) he messages the player/his allies to join in on the siege.

Makes sense. We could make it army size difference for sure, and maybe add a random chance for it like 50%.

**Comment by ByBurton** [comment]
I'd like to have different options here.
-Always active (my take)
- Always active when weaker, 30% active when stronger (Monsterfish's take)
- inactive
- 50% every time
- ...

**Comment by ByBurton** [comment]
<3

**Comment by Monsterfisch** [comment]
like a greased Jesus =)

**Comment by Monsterfisch** [comment]
seems like requesting the ai to attack someone continuously triggers the siege message (testing on shc-e with the opponent needs to be weaker option)

**Comment by J-T-de** [comment]
Question: Do I understand it correctly, that the change only reads some random number (and does not generate a new one? Otherwise, different settings lead to desyncs, which is unnecessary...)

**Comment by Xander10alpha** [comment]
Test it with 1.41 SHC
1.  AI send Siege Message to the Player
2.  in Spectatmode on spectator Maps there send Siege Message to the AI, that i can see

**Comment by ByBurton** [comment]
So what is the current problem with this?
Is it the continuous sending if you ask an ally to attack?
If so can this not be fixed?

**Pull request merged**
