### PR TITLE
LordHansCapon's great "overbuilding workers" revival

### PR DESCRIPTION
**Pull request by LeSpec**

### CODE REVIEW

**Comment by Krarilotus** [comment]
is there anyone who knows hopw this works and can bugfix it?

**Comment by LeSpec** [comment]
> is there anyone who knows hopw this works and can bugfix it?

I changed some addresses, should be working now.

**Comment by ya4k** [comment]
Tested this on its own and it works perfectly well with workers but not military units. Workers with no pathing that end up in a tower despawn and do not get stuck, respawning again at the camp fire. Would it be possible to do the same for peasant women and children as these do not despawn and linger in the towers. The blurb in the GUI states that it can also overbuild soldiers on walls, this is not currently possible.

**Comment by LeSpec** [comment]
Fixed the overbuilding with towers, thx for the hint 👍
In regards to women and children, i don't see an easy way to change that behaviour, but as soon as you build a path to the tower they will leave it eventually.

**Comment by Krarilotus** [comment]
Has this been tested lately?

**Comment by LeSpec** [comment]
There is an improved version for UCP3. Will close this.

**Pull request closed without merging**
