### PR TITLE
Add fix for rapid deletion bug

### PR DESCRIPTION
**Pull request by LeSpec**
Getting more resources by deleting with a fast auto clicker is no longer possible.

Mystical made a video about it:
https://www.youtube.com/watch?v=Yu7fbs8QCkU

Test Build:
https://we.tl/t-MdT9eF7mCI

### CODE REVIEW

**Comment by Heroesflorian** [comment]
Note for potential testers: Please also check if this change has any effect on the map editor: In vanilla, one can place a building, then press Alt+H to stop time, then delete the building multiple times in a row (no time limit) until unfreezing time by pressing Alt+H again. 
This will provide the usual 50% of building cost refund for every time the building was pressed delete on, which is clearly visible e.g. for stockpile resources and gold.

**Comment by LeSpec** [comment]
Good point @Heroesflorian!
Apparently it doesn't work the way i wanted too, so i made some further investigations. I found two solutions to this problem:
1. Delete the building immediately, which, in case the game is paused, leaves you with the unfinished demolishing animation
2. Zero the value for building type, which has side effects. For example, it removes the windmill wheel.

So what should i do, 1., 2. or search for a better solution?

**Comment by Heroesflorian** [comment]
> Apparently it doesn't work the way i wanted to

Does it generally not work as you wanted to, or only for the map editor? 

And if I think about it, for the map editor, it does not really matter - and may actually even be preferable to keep vanilla behaviour if possible, as that saves time when trying to generate a bunch of resources for scenario purposes (and the mapmaker could always just place/delete new buildings anyway; and for instant deletion in editor, there's the landscape erase tool if that's what one wants to do while paused). 

So as long as your fix work reliably during an actual match, it should be fine even if the fix does not change editor behaviour.

**Comment by LeSpec** [comment]
> Does it generally not work as you wanted to, or only for the map editor?

I think it works for clients but not for the host.

Updated with solution 2. It also affects the map editor now.

Test Build:
https://we.tl/t-jQzfUVqxW8

**Comment by gynt** [comment]
> I think it works for clients but not for the host.

Do you want everybody to install this patch? Or do you want a host that has this patch reject users who are abusing this bug? It might be easier to force everybody to use this patch, but maybe not.

**Comment by LeSpec** [comment]
If host has it installed the bug works for no one. Otherwise it only does not work for you.

**Comment by Krarilotus** [comment]
Can we get a tester-review of this one? This change sounds awesome!

**Comment by LeSpec** [comment]
This needs testing still, since i wasn't able to produce the bug in multiplayer.

**Comment by Krarilotus** [comment]
image
I tested today with Ertugal in multiplayer, it worked great, but some buildigns (quarries worked fine) like farms, did have some trouble, because they didn't get deleted al lthe way. I think you need to look into the connection of both instances for these.

@LeSpec other than that, great work!

Tested in extreme, with 40k start gold
-> tested cathedrals
-> tested big towers
-> tested mills
-> tested all bunch of fearfactor buildings

**Comment by LeSpec** [comment]
I still don't fully understand how deletion works, but from my testing it works now.

**Comment by Krarilotus** [comment]
image
We just retested the option, the farm was fixed, but everytime we deleted a building, a new dog would be spawned at one of our hunters!

we haven't tried hutners last time, so i am not sure if it was this way in the last iteration. But do you know why this is the case?

**Comment by LeSpec** [comment]
Good work with the testing!
Looks like i used the wrong function, should use a function inside of the one im currently using. It updates all buildings instead of deleting just one.
I will upload a new version soon.

**Comment by LeSpec** [comment]
Update 3 now open for testing. @Krarilotus
No more spawning dogs, no farm issue.

**Comment by Krarilotus** [comment]
image
seems like a new bug has emerged, sometimes buildings get deleted that shouldt get deleted, Maybe they don't get palced in the first place. It defintly happens to the latest built buildign as soon as you start deleting stuff. but i can't narrow down yet what happens. Look at my stockpile for example!

**Comment by Krarilotus** [comment]
image
so its reproduceable, even when ertu deleted stuff, it sometimes deleted my latest placed buildings. With the stockpile it only deletes some of its isntances which looks really funny. But is the easiest to show off what is wrong. So deleting stuff deletes more than just that but also what was placed latest will also get effected!

**Comment by LeSpec** [comment]
Fingers crossed

**Comment by Krarilotus** [comment]
Just a general thing, but would it be possible to add also some comments to the code on what a section of code does or whats the trick that you use to make it happen? Might help debug stuff later, if any further mistakes are found. Will see if i can test again with Ertu

**Comment by LeSpec** [comment]
Altaruss also mentioned Ertu, does he have Discord?

What the code does:
It checks the logical state of a building (offset 0xD0) which usually is 2, but deleting it sets it to 3. Also manually editing the value to 3 will delete the building.
If logical state = 3, the code will skip the part that is responsible for giving resources back.

I overlooked the logical state variable earlier so i was stumbling in the darkness, now i'm fairly confident it's working since i understand the code that i modified.

**Comment by Krarilotus** [comment]
- Tested in Stronghold Crusader Extreme:
-> tested with autoclicker (tested by Ertu) we also tested without the option to confirm the bug was reproduceable for him
-> tested cathedrals, Towers, Mills and negative fearfactor for rapid deletion bug, all worked fine
-> We tested normal deletion across all buildings on the game, all worked fine
-> Tested worker behaviour and also behaviour of recruits from deleted buildings via recruiting slingers
-> tested farms and quarries and stockpile for their unusual behaviour, all fixed
-> tested hunters for dog spawning, fixed

-> Tested with only host having option enabled, a short resync fixed gold on the client side -> people will be detectable by the lag if they untick the option

-> didn't test moat (not sure why you would need to)
-> didn't test pitch
-> didn't test sleeping buildings yet
-> didn't test with normal Crusader yet

The Fix seems to be all valid. I don't think the options we didn'T test mattered

**Comment by Krarilotus** [comment]
Can you guys show me how its done, and merge the master into the dev branch and this pull request also into the dev branch?

So we can maybe create a dev version that we can use or give out for testing?

**Comment by gynt** [comment]
@Krarilotus Done!

**Pull request merged**
