### PR TITLE
Place killing pits like pitch ditches

### PR DESCRIPTION
**Pull request by LeSpec**
Works for wc and good/bad things too.
Issue #668

Test build:
https://we.tl/t-bZ2tKAs2Xl

### CODE REVIEW

**Comment by LeSpec** [comment]
It's just changing a simple jump, shouldn't produce any bugs. One might have an argument about the included buildings and the time dealy though. (No time delay will spam the command queue.)

**Comment by Krarilotus** [comment]
@LeSpec you said you use this while playing. Can you describe the impact and how you tested it?

Also: Can you split the different things into options? I can imagine a layout like follows, but i am not sure if all the buildings would be possible. It would make it more consistant tho. You could even enable this for siege tents as well...
But if thats too much asked, the buildings i described are the ones that usualy get mass placed, so they probably are the most important ones...
------------------------------------------------------------------------------------------------------------------------------------
Fast placement for buildings:

> With this option you can place small buildings all at once, the same way you place down moat or pitch ditches:
> Enable the buildings you want to be placeable that way:
>> killing pit
>> woodcutter
>> fearfactor building
>> mill
>> waterpot
>> bakeries

If you want the way buildings get placed consistant throughout, you can also select all buildings to be placed in that way:

>> all buildings

**Comment by LeSpec** [comment]
Nested default headers are not possible, right? How would i do this then?

**Comment by LeSpec** [comment]
I have an idea how to do it, but it's ugly and i would have to repeat the code for every d-header. I think it's better to have to options: common once and all builds.

**Comment by Krarilotus** [comment]
what do you mean by nested default headers :D
Like you can do nested options that are ticked all seperately, but the question here is, if you need to recode the whole thing for every building or if its, as you said, a simple skip that can be done for each building individually...

**Comment by LeSpec** [comment]
> what do you mean by nested default headers :D

I mean a default header inside a default header, like this:
```
Enable buildings (default header)
     woodcutter (default header)
     .
     .
All buildings (default header)
```
Ideally i would want a setup like this:
```
new Change
     new DefaultHeader     // enable builds
          new BinaryEdit    // code that is the same for every build
          new Default Header     // woodcutter
          .
          .
     new Default Header     // all builds
```
But from my testing the patcher only allows it like this:
```
new Change
     new Default Header     // woodcutter
          new BinaryEdit    // code that is the same for every build + wood cutter code
     new Default Header     // mill
          new BinaryEdit    // code that is the same for every build + mill code
     .
     .
     new Default Header     // all builds
```
> Like you can do nested options that are ticked all seperately, but the question here is, if you need to recode the whole thing for every building or if its, as you said, a simple skip that can be done for each building individually...

It's one jump that checks whether the selected building is the trap.

**Comment by LeSpec** [comment]
Conflicts resolved, can be tested.

**Pull request merged**
