### PR TITLE
Arabic translation for the UCP

### PR DESCRIPTION
**Pull request by LAITH343**
full translation for UCP patch

### CODE REVIEW

**Review by Ali-Pixiv — APPROVED** [review]
Simple, good wording and easy to understand,
iIapprove

**Review by Ali-Pixiv — APPROVED** [review]
Simple wording, easy to understand ,not too long.
I approve this piece

**Comment by Krarilotus** [comment]
How is this going, are you going to change anthing more ? :D

**Comment by LAITH343** [comment]
> How is this going, are you going to change anthing more ? :D

everything looks good, there's nothing to change for now.  :)

**Pull request merged**
