### PR TITLE
Allow changing gamespeed with non-numpad keys

### PR DESCRIPTION
**Pull request by patel-nikhil**
Allow changing gamespeed with non-numpad +/- keys

### CODE REVIEW

**Comment by Krarilotus** [comment]
Please provide more in deph description which keys will be used instead, also needs a description update of the feature in hte patcher itself

**Comment by patel-nikhil** [comment]
Agree, I can update the UCP description text.

As for which keys: it is the + and - keys that are not on the numpad (without shift modifier fyi).


I feel it is best to describe it as the non-numpad +/- keys, it is the most accurate way to describe it and is the equivalent of how the current behaviour is best described as using the numpad +/- keys.

I am open to suggestion, so let’s confirm this before we update the commit.

**Comment by GRhin** [comment]
The mapping of non numpad + and - keys might be different for different keyboard languages.
Are you using key combinations? For example on a us keyboard the + is achieved by shift =, or is it the = key without shift?

**Comment by LeSpec** [comment]
Maybe the event keycode can clarify any confusions. From my understanding:  + (=171)   - (=173)
https://keycode.info/

**Comment by Krarilotus** [comment]
my own plus would be 187, minus would be 189. hm interesting

**Comment by GRhin** [comment]
Would be good to have this tested by as many different keyboard languages
as possible. German, english us, english uk, russian, chinese, etc.

**Comment by LeSpec** [comment]
I can't figure out what the code does, but to your question, it compares esi with 187 and 189.

**Pull request merged**
