### PR TITLE
added jester doesnt move to assassins on the battlefield fix

### PR DESCRIPTION
**Pull request by Krarilotus**
description: Added a change of one byte to exclude assassins from the troops that the jester visits.

to test: Add assassins and jester in single and multiplayer. @Grhin probably tested this already as he requested this change.

### CODE REVIEW

**Comment by LordHansCapon** [comment]
Doubt it was a bug, more like a deicions. Assassins are invisible and the jester can blow their cover if he entertained them on the battlefield.

**Comment by GRhin** [comment]
> Doubt it was a bug, more like a decision. Assassins are invisible and the jester can blow their cover if he entertained them on the battlefield.

Is there a point you want to make here? Are you trying to suggest it be in a different category or something?
Im sorry, I am not sure what that message was meant to achieve. Just a random opinion that doesnt change anything? or something that should be factored into testing, or implementation?

As for it not being a bug, that depends on your definition. It is definately in a grey area. I doubt the devs deliberately wanted the jester to visit the assassins, and if they had have considered the result, i think they would have made this change themselves. However I dont think they intended to have the jester to not visit either, they simply followed a generic rule "jester visits everything" without considering if the assassin should be an exception or not.

**Comment by Krarilotus** [comment]
@GRhin can this be merged?

**Comment by GRhin** [comment]
Sorry, I have not had time to test yet.

**Comment by Xander10alpha** [comment]
Test it with SHC 1.4.1 and SHC-E 1.41:
1. Player against AIs no Jester go to Assasins
2. AI vs. AI no Jester go to Assasins
3. Need to Test in Multiplayer

**Pull request merged**
