### PR TITLE
Fix assassin pathing and behaviour

### PR DESCRIPTION
**Pull request by LordHansCapon**
- Assassins will no longer stop and forget their destination in the middle of the map after encountering an enemy on the way
- Assassins will no longer attack units on atop the keep after descending the wall into a 1 tile gap path between the wall and the keep

See #632

### CODE REVIEW

**Comment by LordHansCapon** [comment]
**Important:** There is another bug with the assassins which this bug fix does not solve. When you order an assassin to climb an outer wall, and he attacks an enemy on the way there. The assassin will just stand next to the wall upon arrival and does not scale it. If you order the assassin on the other side of the wall, or an inner wall, then it works just fine. This may be solved in a different bugfix, but I just could not solve this issue.

Still, this fix is good enough I think.

**Comment by LordHansCapon** [comment]
The link below contains this PR's test build:
https://we.tl/t-2VWVuNxpfD

Files in zip:
- UnofficialCrusaderPatch.dll (38 287 872 bytes)
- UnofficialCrusaderPatchGUI.exe (122 368 bytes)

**Comment by LordHansCapon** [comment]
WeTransfer link update:
https://we.tl/t-Grs1GptXpS

**Comment by JuGGerNaunT** [comment]
Don't know if it is intended behavior, but in this bugfix you completely remove descending action for assassin. So instead of actual climbing down, assassin just teleport to the ground.

**Comment by Krarilotus** [comment]
@JuGGerNaunT how did this appear? For me the assassins had a normal animation. Can you give us a way to recrete the issue? For me it works fine!

**Pull request merged**
