### PR TITLE
Project url fix

### PR DESCRIPTION
**Pull request by StrongholdOverlordsMod**
Description contained old links that were redirected, help button contained a link leading to 404.

### CODE REVIEW

**Comment by Krarilotus** [comment]
This looks good, tho the link is wrong.
The link would be:
https://unofficialcrusaderpatch.github.io/UnofficialCrusaderPatch

We also are going to change the link adress once more to this one (which is already up and running):
https://unofficialcrusaderpatch.github.io/

**Comment by StrongholdOverlordsMod** [comment]
Hello,
thanks for the info.
I made a new commit with the new url.
This is my first time working with github so if there is something else i need to do, please let me know.
Thanks.

**Comment by Krarilotus** [comment]
Ah wait, i think i made a mistake :D
The link to the github was correct, just the one behind the little ? button was the one, that i ment. Sorry, this was really awefull commen there by me.

Thanks for the work, appriciate it :D Even if its small things, it helps!

**Comment by StrongholdOverlordsMod** [comment]
No problem.

I was thinking if the new url applies to both cases, and as the url provided contains well visible download link at top i thought it would apply well for both so i changed all urls 👯.

I made a new commint where help url contains "https://unofficialcrusaderpatch.github.io/" and project url in description contains "https://github.com/UnofficialCrusaderPatch/UnofficialCrusaderPatch".

Btw im especially happy that i got a quick response and you are welcoming 3rd party commits, its what i was trying to probe with this small commit and with this i ll be happy to jump to cli/gui updates ive got in mind (first is resizeable installer gui i guess, as the existing fork seems to be stale and there is an issue filled for that, also its annoying for me aswell :p).

Let me know if there any issue now.

Thanks.

**Comment by Krarilotus** [comment]
@StrongholdOverlordsMod sweet! I think it would be great, if you could join our discord, so i can invite you to the team. We are currently working on a complete backend rework, meaning we also will probably have a new API to talk to a gui soon.

The GUI will then be repurposed for the time being to create just a config file, which we also want to get into a json or yaml format to reduce the propriatary solutions and make code more understandable and readable for new devs.

In the future we are thinking about integrating the UCP right into the game (loading full packaged mods inside of the game would be the dream without re-installing and sorting files every time ^^), where it make sense ofc, but still have a way to lock changes on runtime for multiplayer games or other applications where the modder wants to have control.

But long story short, if you want to put work into CLI and GUI, that is very welcome! We would love someone who can design a more functional and well designed gui, in which not all options are cluttered in together as is right now. So it would also be greatly appriciated, if you could post some design ideas and have some forth and back discussions in our team chat.

If you feel a bit overwhelemed by this, and wanted just to fix some bugs thats also fine, but just wanted to post an invitation :) (Discord link is on both, the website and the github front page)

**Pull request merged**
