### PR TITLE
disable border scrolling

### PR DESCRIPTION
**Pull request by LeSpec**
Download link:
https://we.tl/t-L8XDEp06fG

### CODE REVIEW

**Comment by TheRedDaemon** [comment]
Checked the test build on 1.41 and 1.41.1-E:
Installs and works as intended. ("scrollen" in the German description needs a capital "c", though. 🙃 )

*Little note*
This feature enables a nice configuration for the program DxWnd that allows to keep the game and the rendering running, despite being not focused. [Small config guide](https://github.com/Sh0wdown/UnofficialCrusaderPatch/issues/765#issuecomment-803441567) Pretty handy for checking game behaviors with Cheat Engine.

**Comment by Krarilotus** [comment]
System.Exception: u_spearmen_run_descr Missing closing bracket at line 23
   bei UCP.Localization.Load(Int32 index)

Got the following exception when startin the GUI

**Comment by LeSpec** [comment]
Some brackets go accidentally removed in the last merge. Fixed now, try again

**Comment by Krarilotus** [comment]
@LeSpec could you sort out the localization one more time, so we can merge this into a development testing build?
Would be greatly appriciated!
:))

**Comment by LeSpec** [comment]
@Krarilotus Done

**Comment by Krarilotus** [comment]
@LeSpec why does it say it has conflicts o.O

**Comment by gynt** [comment]
> @LeSpec why does it say it has conflicts o.O

Because we changed branch to development !
@LeSpec Can you bring the branch up to speed with the development branch? :)

**Pull request merged**
